# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "HMKCODE"

author:
  facebook:         hmkcode
  twitter:          hmkcode
  github:           hmkcode
  googlePlus:       +hmkcode

copyright:
  year:             2017
  name:             hmkcode

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "hmkcode"

# URL
url:                "http://hmkcode.com" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:categories/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-paginate

exclude:            [vendor]